AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  AuthorizedAccount: 
    Type: String
Resources: 
  AssumeRoleAdmin: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Join
                  - ":"
                  - - "arn:aws:iam:"
                    - !Ref AuthorizedAccount
                    - "root"
            Action: 
              - "sts:AssumeRole"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "true"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      RoleName: "AssumeRole-Administrator"